############################################################
#                                                          #
#               V i p e r E l e v a t o r s                #
#                                                          #
#  Author: Expectatives                                    #
#  Version: 0.6                                            #
#  Discord: Expectatives#1157                              #
#  Discord Server: https://dsc.gg/faithcommunity/          #
#                                                          #
############################################################

# ELEVATOR SIGN CONFIGURATION
ELEVATOR-SIGN:
  TITLE: "&c[Elevator]"
  BREAK-MESSAGE: "&cWrong format"
  NO-FOUND-MESSAGE: "&cCould not find valid teleport location!"
