############################################################
#                                                          #
#       V i p e r E l e v a t o r s  S N A P S H O T       #
#                                                          #
#  Authors: Expectatives                                   #
#  Version: 0.1-SNAPSHOT                                   #
#  Discord: Expectatives#1157                              #
#  Discord Server: https://discord.faithcommunity.club/    #
#                                                          #
############################################################

# ELEVATOR SIGN CONFIGURATION
ELEVATOR_SIGN:
  TITLE: "&c[Elevator]"
  BREAK_MESSAGE: "&cWrong format"
  NO_FOUND_MESSAGE: "&cCould not find valid teleport location!"